### PR TITLE
Added support for importing external references

### PR DESCRIPTION
**Pull request by ghost**
- added support for importing external references (not module mode only)
- added ``ExceptionForUser`` for showing error message to user

### CODE REVIEW

**Comment by denis-peshkov** [comment]
Hi, sorry for so much time for answer, will try review it asap

**Comment by denis-peshkov** [comment]
Hey @LukeOwlclaw , again sorry, for the late response,.
Just now I finished testing and have some issues. 

Could you take a look at newly added test **_ShouldWorkProperly2**? After merge your changes test has been fallen. 

Currently I get:
`
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS7036	There is no argument given that corresponds to the required formal parameter 'sourceItemPath' of 'IntellisenseWriter.WriteTypeScript(IEnumerable<IntellisenseObject>, string)'	TypeScriptDefinitionGenerator.Tests	P:\github.com\TypeScriptDefinitionGenerator\tests\TypeScriptDefinitionGenerator.Tests\IntellisenseParserTest.cs	166	N/A
Error		Custom tool DtsGenerator failed to produce an output for input file 'SomeClass.cs' but did not log a specific error.	ClassLibrary1	P:\github.com\TypeScriptDefinitionGenerator\tests\ClassLibrary1\SomeClass.cs	1	
`

Also, be sure that the **_ShouldWorkProperly** test is not broken.

**Comment by ghost** [comment]
I just merged master into my branch. I am getting two compile errors originating from `IntellisenseParserTest.cs` lines 68 and 182, both:

    var tsFile = IntellisenseWriter.WriteTypeScript(list);

But `WriteTypeScript` requires a second parameter. Is there a commit missing?

**Comment by denis-peshkov** [comment]
Hi,  that's what exactly I want you to fix. I created tests, and they work fine before your changes. Unfortunately, I can't configure to build tests automatically. By the way, you can and have do it manually before create a MR. 

But, let me check once more time about parameters. Will do in few hours.

**Comment by ghost** [comment]
Sorry! Yes, now I understand. I thought it is about a failing test. I'll have a look!

**Comment by ghost** [comment]
Okay, fixed it. I also added a new test method together with new (complex) TS types / C# classes.

**Comment by denis-peshkov** [comment]
Hi again, did you run tests locally? How I can see, there problem with it.

image

**Comment by ghost** [comment]
Yes, all tests passing for me:
image

What error message are you seeing? Were all ts successfully generated? `SomeEnum.generated.ts`?

**Comment by denis-peshkov** [comment]
image

**Comment by denis-peshkov** [comment]
image

**Comment by denis-peshkov** [comment]
Yep, I so sorry, It was my fail, I tested it when few Visual Studios were opened.

**Comment by denis-peshkov** [comment]
```
TypeScript Definition Generator: Using Global Settings
TypeScript Definition Generator: SomeClass.cs - Started
TypeScript Definition Generator: SomeClass.cs - Completed
TypeScript Definition Generator: Using Global Settings
TypeScript Definition Generator: SomeEnum.cs - Started
TypeScript Definition Generator: SomeEnum.cs - Completed
TypeScript Definition Generator: Using Global Settings
TypeScript Definition Generator: SomeSomeClass.cs - Started
TypeScript Definition Generator: SomeSomeClass.cs - Completed
TypeScript Definition Generator: Using Global Settings
TypeScript Definition Generator: SecondClass.cs - Started
TypeScript Definition Generator: SecondClass.cs - Completed
TypeScript Definition Generator: Using Global Settings
TypeScript Definition Generator: Class1.cs - Started
TypeScript Definition Generator: Class1.cs - Completed
TypeScript Definition Generator: Class1.cs - Failure
```
and finally 
```
TypeScript Definition Generator: Sorry, needed imports missing: IntEnum, SomeClass, SomeEnum, SomeSomeClass.Make sure file names match contained class/enum name.
```
@LukeOwlclaw  how do you expect to do it in new generation?

Like for me better then throw an exception write this message into just generated .ts file. Developer will see that some actions needed and provide them.
In future, perhaps, will fix it by adding implementation for this case.

**Pull request merged**
